name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cache:
    runs-on: ubuntu-latest
    outputs:
      npm-cache-hit: ${{ steps.npm-cache.outputs.cache-hit }}
      pw-cache-hit: ${{ steps.pw-cache.outputs.cache-hit }}
      next-cache-hit: ${{ steps.next-cache.outputs.cache-hit }}
    steps:
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache@v3
        id: pw-cache
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ hashFiles('package-lock.json') }}

      - uses: actions/cache@v3
        id: next-cache
        with:
          path: .next/cache
          key: next-${{ hashFiles('package-lock.json') }}

  test-unit:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:unit

  test-e2e:
    needs: cache
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
        env:
          BASE_URL: ${{ vars.BASE_URL }}

  build:
    needs: [test-unit, test-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Copy static files to standalone
        run: |
          mkdir -p .next/standalone/.next/static
          cp -r .next/static/* .next/standalone/.next/static/
          cp -r public .next/standalone/

      - name: Upload standalone build
        uses: actions/upload-artifact@v4
        with:
          name: standalone-build
          path: .next/standalone
          if-no-files-found: warn

      - name: Upload static files
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: |
            .next/static
            public
          if-no-files-found: warn

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            !.next/cache/**
          if-no-files-found: warn
