name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cache-npm:
    uses: ./.github/workflows/cache.yml
    with:
      cache-type: 'npm'

  cache-playwright:
    uses: ./.github/workflows/cache.yml
    with:
      cache-type: 'playwright'

  cache-nextjs:
    uses: ./.github/workflows/cache.yml
    with:
      cache-type: 'nextjs'

  test-unit:
    needs: cache-npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  test-e2e:
    needs: [cache-npm, cache-playwright]
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          BASE_URL: ${{ vars.BASE_URL }}

  build:
    needs: [test-unit, test-e2e, cache-nextjs]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: List build output
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo ".next directory contents:"
          ls -la .next/ || echo ".next directory not found"
          echo "Standalone directory contents:"
          ls -la .next/standalone/ || echo "standalone directory not found"

      - name: Upload standalone build
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: standalone-build
          path: .next/standalone
          if-no-files-found: warn

      - name: Upload static files
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: static-files
          path: |
            .next/static
            public
          if-no-files-found: warn

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-output
          path: |
            .next
            !.next/cache/**
          if-no-files-found: warn